#ifndef MBEDTLS_CONFIG_H
#define MBEDTLS_CONFIG_H

#define MBEDTLS_CONFIG_VERSION 0x04000000

#ifndef PSA_WANT_ALG_SHA_256
#define PSA_WANT_ALG_SHA_256
#endif
#ifndef PSA_WANT_ALG_SHA_384
#define PSA_WANT_ALG_SHA_384
#endif
#ifndef PSA_WANT_ALG_HKDF
#define PSA_WANT_ALG_HKDF
#endif
#ifndef PSA_WANT_ALG_HMAC
#define PSA_WANT_ALG_HMAC
#endif

#ifndef PSA_WANT_ALG_ECDH
#define PSA_WANT_ALG_ECDH
#endif
#ifndef PSA_WANT_ALG_ECDSA
#define PSA_WANT_ALG_ECDSA
#endif
#ifndef PSA_WANT_ECC_SECP_R1_256
#define PSA_WANT_ECC_SECP_R1_256
#endif
#ifndef PSA_WANT_ECC_SECP_R1_384
#define PSA_WANT_ECC_SECP_R1_384
#endif

#ifndef PSA_WANT_ALG_CHACHA20_POLY1305
#define PSA_WANT_ALG_CHACHA20_POLY1305
#endif
#ifndef PSA_WANT_ALG_GCM
#define PSA_WANT_ALG_GCM
#endif

#define MBEDTLS_NET_C
#define MBEDTLS_TIMING_C
#define MBEDTLS_HAVE_TIME

#define MBEDTLS_PSA_CRYPTO_C
#define MBEDTLS_PSA_CRYPTO_CLIENT
#define MBEDTLS_PK_C
#define MBEDTLS_PK_PARSE_C
#define MBEDTLS_PK_WRITE_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_ASN1_WRITE_C

#define MBEDTLS_ERROR_C
#define MBEDTLS_ERROR_STRERROR_DUMMY
#define MBEDTLS_VERSION_C

#define MBEDTLS_DEBUG_C
#define MBEDTLS_SSL_TLS_C
#define MBEDTLS_SSL_CLI_C
#define MBEDTLS_SSL_SRV_C

#define MBEDTLS_SSL_PROTO_TLS1_2
#define MBEDTLS_SSL_PROTO_TLS1_3
#define MBEDTLS_SSL_PROTO_DTLS

#define MBEDTLS_SSL_VARIABLE_BUFFER_LENGTH
#define MBEDTLS_SSL_MAX_FRAGMENT_LENGTH

#define MBEDTLS_SSL_DTLS_ANTI_REPLAY
#define MBEDTLS_SSL_DTLS_CLIENT_PORT_REUSE
#define MBEDTLS_SSL_DTLS_CONNECTION_ID
#define MBEDTLS_SSL_DTLS_HELLO_VERIFY
#define MBEDTLS_SSL_COOKIE_C

#define MBEDTLS_SSL_ALPN
#define MBEDTLS_SSL_CACHE_C
#define MBEDTLS_SSL_CONTEXT_SERIALIZATION
#define MBEDTLS_SSL_EXTENDED_MASTER_SECRET
#define MBEDTLS_SSL_KEEP_PEER_CERTIFICATE
#define MBEDTLS_SSL_KEYING_MATERIAL_EXPORT
#define MBEDTLS_SSL_SERVER_NAME_INDICATION
#define MBEDTLS_SSL_SESSION_TICKETS
#define MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE

#define MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED
#define MBEDTLS_KEY_EXCHANGE_PSK_ENABLED

#define MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_EPHEMERAL_ENABLED
#define MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_ENABLED
#define MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_EPHEMERAL_ENABLED

#define MBEDTLS_X509_USE_C
#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_X509_CRL_PARSE_C
#define MBEDTLS_X509_CSR_PARSE_C
#define MBEDTLS_X509_CREATE_C
#define MBEDTLS_X509_CRT_WRITE_C
#define MBEDTLS_X509_CSR_WRITE_C

#endif /* MBEDTLS_CONFIG_H */